### ISSUE TITLE
New Issue

### ISSUE THREAD

**Issue by tienne** [playauto/welcome#3]
이슈테스트입니다.

**Comment by tienne** [comment]
@byseob 이슈발생입니다.

**Comment by 480** [comment]
@tienne 알림 노티는 따로 없군 서드파티를 써야하나.

**Comment by tienne** [comment]
@byseob 알림 테스트~

**Comment by 480** [comment]
![image](https://cloud.githubusercontent.com/assets/13383972/12668322/ae97b504-c698-11e5-824e-9383c86d75c7.png)

@tienne 이미지 복붙도 잘 됨.

**Comment by 480** [comment]
_마크업은 같음._

```
이건 긴 문장
소스코드 처리
```

~~취소선 처리~~
